### ISSUE TITLE
L4 support

### ISSUE THREAD

**Issue by hadifarnoud** [jschutt/Statamic-Mandrill-Form#1]
Is this package Laravel 5 only? can you make it a bit more clear in the readme please?

**Comment by jschutt** [comment]
Hi @hadifarnoud  - This is not a Laravel package at all. It's a plugin for Statamic version 1.x. Does this answer your question?

**Comment by hadifarnoud** [comment]
that would be a cool package for Laravel 4/5 though. I would've helped if I could

**Comment by jschutt** [comment]
@hadifarnoud I'll see what I can do!
